### ISSUE TITLE
Issue installing Cinnamon on Sandbox org

### ISSUE THREAD

**Issue by alokbehera** [forcedotcom/cinnamon#45]
Hi,

I have installed Cinnamon on Sandbox org and the installation is successful. however when I tried opening the Cinnamon app I am getting the below error. 

Error: Previous load of class failed: testDate: line 189, column 13: Variable does not exist: TimeZone 

Could you please help.

Regards,
Alok

**Comment by yudiatsfdc** [comment]
It sounds like you have a class named testDate that has a syntax error. Cinnamon uses a prefix to identify tests it should run, and the default out of the box is 'Test'. If you already have classes starting with this prefix, it will try to instantiate it, and that's why you're getting this error. To work around it you can:
a) use a diffferent prefix for Cinnamon tests. Go to the settings tab and enter a different prefix, or
b) fix any previous class compile errors for classes that start with 'Test'
